# Generated by Django 2.1.5 on 2019-08-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('num', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='订单号')),
                ('title', models.CharField(max_length=100, verbose_name='订单名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单金额')),
                ('pay_type', models.IntegerField(choices=[(0, '余额支付'), (1, '银联支付'), (2, '支付宝'), (3, '微信支付')], default=0, verbose_name='支付方式')),
                ('pay_status', models.IntegerField(choices=[(0, '待支付'), (1, '已支付'), (2, '待收货'), (3, '已收货'), (4, '完成'), (5, '已取消')], default=0, verbose_name='订单状态')),
                ('receive', models.CharField(max_length=20, verbose_name='收货人')),
                ('receive_phone', models.CharField(max_length=11, verbose_name='收货人电话')),
                ('receive_address', models.TextField(verbose_name='收获地址')),
            ],
            options={
                'verbose_name': '订单表',
                'verbose_name_plural': '订单表',
                'db_table': 't_order',
            },
        ),
    ]
