# Generated by Django 2.1.5 on 2019-08-28 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_fruitcartentity'),
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive', models.CharField(max_length=20, verbose_name='收货人')),
                ('receive_phone', models.CharField(max_length=11, verbose_name='收货人电话')),
                ('receive_address', models.TextField(verbose_name='收获地址')),
            ],
            options={
                'verbose_name': '收货详情',
                'verbose_name_plural': '收货详情',
                'db_table': 't_adress',
            },
        ),
        migrations.CreateModel(
            name='OrderParticularsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cnt', models.IntegerField(default=1, verbose_name='商品数量')),
                ('pay_type', models.IntegerField(choices=[(0, '余额支付'), (1, '银联支付'), (2, '支付宝'), (3, '微信支付')], default=0, verbose_name='支付方式')),
                ('pay_status', models.IntegerField(choices=[(0, '待支付'), (1, '已支付'), (2, '待收货'), (3, '已收货'), (4, '完成'), (5, '已取消')], default=0, verbose_name='订单状态')),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.FruitEntity', verbose_name='商品id')),
            ],
            options={
                'verbose_name': '订单详情表',
                'verbose_name_plural': '订单详情表',
                'db_table': 't_orderparticulars',
            },
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='last_time',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='pay_status',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='pay_type',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='receive',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='receive_address',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='receive_phone',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserEntity', verbose_name='用户id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderparticularsmodel',
            name='num_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderapp.OrderModel', verbose_name='订单号'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='address_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orderapp.AddressModel', verbose_name='收货地址id'),
            preserve_default=False,
        ),
    ]
