# Generated by Django 2.1.5 on 2019-08-29 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0003_addressmodel_u_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='address_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderapp.AddressModel', verbose_name='收货地址'),
        ),
        migrations.AlterField(
            model_name='orderparticularsmodel',
            name='num_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderapp.OrderModel', verbose_name='订单名称'),
        ),
    ]
