# Generated by Django 2.1.5 on 2019-08-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeentity',
            name='id',
            field=models.UUIDField(default='78a76ba5d7da46b2950149977269a0c8', primary_key=True, serialize=False, verbose_name='店号'),
        ),
    ]
