# Generated by Django 2.1.5 on 2019-08-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190827_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeentity',
            name='id',
            field=models.UUIDField(default='58efaa2074c14b069519afea847f83bd', primary_key=True, serialize=False, verbose_name='店号'),
        ),
    ]
