# Generated by Django 2.1.5 on 2019-08-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20190827_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeentity',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name='店号'),
        ),
    ]
