# Generated by Django 2.1.5 on 2019-08-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190827_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeentity',
            name='logo',
            field=models.ImageField(blank=True, height_field='logo_height', null=True, upload_to='store', verbose_name='LOGO', width_field='logo_width'),
        ),
        migrations.AddField(
            model_name='storeentity',
            name='logo_height',
            field=models.IntegerField(null=True, verbose_name='LOGO height'),
        ),
        migrations.AddField(
            model_name='storeentity',
            name='logo_width',
            field=models.IntegerField(null=True, verbose_name='LOGO width'),
        ),
        migrations.AddField(
            model_name='storeentity',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='介绍'),
        ),
    ]
