# Generated by Django 2.1.5 on 2019-08-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20190827_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeentity',
            name='opened',
            field=models.BooleanField(default=False, verbose_name='是否开业'),
        ),
    ]
