# Generated by Django 2.1.5 on 2019-08-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_fruitimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitimage',
            name='url',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='fruit', verbose_name='图片存放路径'),
        ),
    ]
