# Generated by Django 2.1.5 on 2019-08-28 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_realprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserEntity', verbose_name='账号'),
        ),
    ]
