# Generated by Django 2.1.5 on 2019-08-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_fruitcartentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruitentity',
            name='users',
            field=models.ManyToManyField(db_table='t_collect', related_name='fruits', to='mainapp.UserEntity', verbose_name='收藏用户列表'),
        ),
    ]
