# Generated by Django 2.1.5 on 2019-08-29 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20190829_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPasswordEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=10, verbose_name='密码')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserEntity', verbose_name='账号')),
            ],
            options={
                'verbose_name': '用户密码表',
                'verbose_name_plural': '用户密码表',
                'db_table': 't_password',
            },
        ),
        migrations.AlterField(
            model_name='fruitentity',
            name='tags',
            field=models.ManyToManyField(blank=True, db_table='t_fruit_tags', null=True, related_name='fruits', to='mainapp.TagEntity', verbose_name='所有标签'),
        ),
        migrations.AlterField(
            model_name='fruitentity',
            name='users',
            field=models.ManyToManyField(blank=True, db_table='t_collect', null=True, related_name='fruits', to='mainapp.UserEntity', verbose_name='收藏用户列表'),
        ),
        migrations.AlterField(
            model_name='realprofile',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='user/real', verbose_name='正面照'),
        ),
        migrations.AlterField(
            model_name='realprofile',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='user/real', verbose_name='反面照'),
        ),
    ]
