# Generated by Django 2.1.5 on 2019-08-30 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20190829_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpasswordentity',
            name='users',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserEntity', verbose_name='账号'),
        ),
    ]
