# Generated by Django 2.1.5 on 2019-08-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20190830_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpasswordentity',
            name='users',
        ),
        migrations.AddField(
            model_name='userentity',
            name='password',
            field=models.CharField(default=1, max_length=10, verbose_name='密码'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserPasswordEntity',
        ),
    ]
